version: '3.6'
services:

  stage1:
    build:
        context: .
        cache_from:
        - debian:latest
        - tmp/multistage/01:stage_stage1
        target: stage1        
    image: tmp/multistage/01:stage_stage1
    
  stage2:
    build:
        context: .
        cache_from:
        - debian:latest
        - tmp/multistage/01:stage_stage2
        target: stage2
    image: tmp/multistage/01:stage_stage2

  final:
    build:
        context: .
        cache_from:
        - debian:latest
        - tmp/multistage/01:stage_stage1
        - tmp/multistage/01:stage_stage2
        - tmp/multistage/01:final
    image: tmp/multistage/01:final

    
# docker rmi tmp/multistage/01:stage_stage1 tmp/multistage/01:stage_stage2 tmp/multistage/01:final && docker system prune
