version: '3.6'
services:

  stage1:
    build:
        context: .
        cache_from:
        - debian:latest
        - tmp/multistage/03:stage_stage1
        target: stage1        
    image: tmp/multistage/03:stage_stage1
    
  stage2:
    build:
        context: .
        cache_from:
        - tmp/multistage/03:stage_stage1
        - tmp/multistage/03:stage_stage2
        target: stage2
    image: tmp/multistage/03:stage_stage2

  final:
    build:
        context: .
        cache_from:
        - debian:latest
        - tmp/multistage/03:stage_stage1
        - tmp/multistage/03:stage_stage2
        - tmp/multistage/03:final
    image: tmp/multistage/03:final

# docker rmi tmp/multistage/03:stage_stage1 tmp/multistage/03:stage_stage2 tmp/multistage/03:final && docker system prune
